# Copyright 2021 Pants project contributors.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

[GLOBAL]
pants_version = "2.21.0"
backend_packages = ["pants.backend.experimental.go"]

[anonymous-telemetry]
enabled = true
repo_id = "AE018A26-213E-4B18-99A6-6923EC1E16DE"

[golang]
minimum_expected_version = "1.19"
